In [1]:
import pandas as pd
import numpy as np

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 20)

In [2]:
# Load CPU Datasets
cpu1 = pd.read_csv(
    r"C:\Users\Avilasha\Desktop\CPU_Predictive_Maintenance\CPU\data\Raw\Datacenter Datas 11.06.2026 to 18.06.2026\SERVER WISE DATA\host_metrics_host1.csv"
)
server1_resource = pd.read_csv(
    r"C:\Users\Avilasha\Desktop\CPU_Predictive_Maintenance\CPU\data\Raw\Datacenter Datas 11.06.2026 to 18.06.2026\SERVER WISE DATA\ilo_server_metrics_iloserver1.csv",
    usecols=[
        "ts",
        "ilo_server_id",
        "inlet_temp_c",
        "cpu_temp_c",
        "processor_count"
    ]
)

cpu2 = pd.read_csv(
    r"C:\Users\Avilasha\Desktop\CPU_Predictive_Maintenance\CPU\data\Raw\Datacenter Datas 11.06.2026 to 18.06.2026\SERVER WISE DATA\host_metrics_host2.csv"
)
server2_resource = pd.read_csv(
    r"C:\Users\Avilasha\Desktop\CPU_Predictive_Maintenance\CPU\data\Raw\Datacenter Datas 11.06.2026 to 18.06.2026\SERVER WISE DATA\ilo_server_metrics_iloserver2.csv",
    usecols=[
        "ts",
        "ilo_server_id",
        "inlet_temp_c",
        "cpu_temp_c",
        "processor_count"
    ]
)

cpu3 = pd.read_csv(
    r"C:\Users\Avilasha\Desktop\CPU_Predictive_Maintenance\CPU\data\Raw\Datacenter Datas 11.06.2026 to 18.06.2026\SERVER WISE DATA\host_metrics_host3.csv"
)
server3_resource = pd.read_csv(
    r"C:\Users\Avilasha\Desktop\CPU_Predictive_Maintenance\CPU\data\Raw\Datacenter Datas 11.06.2026 to 18.06.2026\SERVER WISE DATA\ilo_server_metrics_iloserver3.csv",
    usecols=[
        "ts",
        "ilo_server_id",
        "inlet_temp_c",
        "cpu_temp_c",
        "processor_count"
    ]
)

In [3]:
# inspect CPU Datasets
print("CPU1")
display(cpu1.head())
print("server1_resource")
display(server1_resource.head())

print("CPU2")
display(cpu2.head())
print("server2_resource")
display(server2_resource.head())

print("CPU3")
display(cpu3.head())
print("server3_resource")
display(server3_resource.head())

CPU1

,id,ts,host_id,cpu_usage_pct,memory_usage_pct,power_kw,temperature_c,status
0,74125,2026-06-11 00:01:37.268+00,1,2.03,81.65,0.220,27,Warning
1,74128,2026-06-11 00:06:36.561+00,1,2.03,81.65,0.221,28,Warning
2,74131,2026-06-11 00:11:42.33+00,1,1.88,81.65,0.220,23,Warning
3,74134,2026-06-11 00:16:37.251+00,1,2.78,81.65,0.221,20,Warning
4,74137,2026-06-11 00:21:36.482+00,1,3.31,81.65,0.220,25,Warning

server1_resource

,ts,ilo_server_id,inlet_temp_c,cpu_temp_c,processor_count
0,2026-04-06 11:01:22.401+00,1,21,38,2
1,2026-04-06 11:03:25.864+00,1,20,38,2
2,2026-04-06 11:05:18.288+00,1,20,38,2
3,2026-04-06 11:07:18.226+00,1,20,39,2
4,2026-04-06 11:09:20.245+00,1,20,38,2

CPU2

,id,ts,host_id,cpu_usage_pct,memory_usage_pct,power_kw,temperature_c,status
0,74126,2026-06-11 00:01:37.268+00,2,2.24,20.39,0.208,26,Normal
1,74129,2026-06-11 00:06:36.561+00,2,1.28,21.17,0.209,28,Normal
2,74132,2026-06-11 00:11:42.33+00,2,1.20,21.17,0.207,23,Normal
3,74135,2026-06-11 00:16:37.251+00,2,1.41,21.17,0.239,21,Normal
4,74138,2026-06-11 00:21:36.482+00,2,1.20,21.17,0.245,25,Normal

server2_resource

,ts,ilo_server_id,inlet_temp_c,cpu_temp_c,processor_count
0,2026-06-11 00:01:37.268+00,2,26,43,2
1,2026-06-11 00:06:36.561+00,2,28,43,2
2,2026-06-11 00:11:42.33+00,2,23,42,2
3,2026-06-11 00:16:37.251+00,2,21,41,2
4,2026-06-11 00:21:36.482+00,2,25,42,2

CPU3

,id,ts,host_id,cpu_usage_pct,memory_usage_pct,power_kw,temperature_c,status
0,74124,2026-06-10 23:56:36.57+00,3,27.96,27.0,0.209,22,Normal
1,74127,2026-06-11 00:01:37.268+00,3,29.01,27.0,0.212,25,Normal
2,74130,2026-06-11 00:06:36.561+00,3,29.22,27.0,0.212,26,Normal
3,74133,2026-06-11 00:11:42.33+00,3,27.54,27.0,0.210,21,Normal
4,74136,2026-06-11 00:16:37.251+00,3,27.44,27.0,0.211,18,Normal

server3_resource

,ts,ilo_server_id,inlet_temp_c,cpu_temp_c,processor_count
0,2026-06-11 00:01:37.268+00,3,25,46,2
1,2026-06-11 00:06:36.561+00,3,26,49,2
2,2026-06-11 00:11:42.33+00,3,21,46,2
3,2026-06-11 00:16:37.251+00,3,18,43,2
4,2026-06-11 00:21:36.482+00,3,23,45,2

In [4]:
# Check column names
print(cpu1.columns)
print(cpu2.columns)
print(cpu3.columns)
print(server1_resource.columns)
print(server2_resource.columns)
print(server3_resource.columns)

Index(['id', 'ts', 'host_id', 'cpu_usage_pct', 'memory_usage_pct', 'power_kw',
       'temperature_c', 'status'],
      dtype='object')
Index(['id', 'ts', 'host_id', 'cpu_usage_pct', 'memory_usage_pct', 'power_kw',
       'temperature_c', 'status'],
      dtype='object')
Index(['id', 'ts', 'host_id', 'cpu_usage_pct', 'memory_usage_pct', 'power_kw',
       'temperature_c', 'status'],
      dtype='object')
Index(['ts', 'ilo_server_id', 'inlet_temp_c', 'cpu_temp_c', 'processor_count'], dtype='object')
Index(['ts', 'ilo_server_id', 'inlet_temp_c', 'cpu_temp_c', 'processor_count'], dtype='object')
Index(['ts', 'ilo_server_id', 'inlet_temp_c', 'cpu_temp_c', 'processor_count'], dtype='object')

In [5]:
# convert timestamp columns
cpu1["ts"] = pd.to_datetime(
    cpu1["ts"],
    format="mixed",
    utc=True
)

cpu2["ts"] = pd.to_datetime(
    cpu2["ts"],
    format="mixed",
    utc=True
)

cpu3["ts"] = pd.to_datetime(
    cpu3["ts"],
    format="mixed",
    utc=True
)

server1_resource["ts"] = pd.to_datetime(
    server1_resource["ts"],
    format="mixed",
    utc=True
)

server2_resource["ts"] = pd.to_datetime(
    server2_resource["ts"],
    format="mixed",
    utc=True
)

server3_resource["ts"] = pd.to_datetime(
    server3_resource["ts"],
    format="mixed",
    utc=True
)

In [6]:
# verify dataset size
print(cpu1.shape)
print(cpu2.shape)
print(cpu3.shape)

print("\nTotal rows expected:")
print(len(cpu1) + len(cpu2) + len(cpu3))

(2124, 8)
(2124, 8)
(2125, 8)

Total rows expected:
6373

In [7]:
HOST_MAP = {
    1: "10.10.10.65",
    2: "10.10.10.150",
    3: "10.10.10.2"
}
cpu1["hostName"] = cpu1["host_id"].map(HOST_MAP)

cpu2["hostName"] = cpu2["host_id"].map(HOST_MAP)

cpu3["hostName"] = cpu3["host_id"].map(HOST_MAP)

In [8]:
# combining all CPU Datasets
server1 = pd.merge(
    cpu1,
    server1_resource,
    left_on=["ts", "host_id"],
    right_on=["ts", "ilo_server_id"],
    how="inner"
)

server2 = pd.merge(
    cpu2,
    server2_resource,
    left_on=["ts", "host_id"],
    right_on=["ts", "ilo_server_id"],
    how="inner"
)

server3 = pd.merge(
    cpu3,
    server3_resource,
    left_on=["ts", "host_id"],
    right_on=["ts", "ilo_server_id"],
    how="inner"
)

print(server1.shape)
print(server2.shape)
print(server3.shape)

(2124, 13)
(2124, 13)
(2124, 13)

In [9]:
cpu_master_new = pd.concat(
    [server1, server2, server3],
    ignore_index=True
)

HOST_MAP = {
    1: "10.10.10.65",
    2: "10.10.10.150",
    3: "10.10.10.2"
}

cpu_master_new["hostName"] = (
    cpu_master_new["host_id"]
    .map(HOST_MAP)
)
cpu_master_new.shape

(6372, 13)

In [10]:
# inspect combined dataset
cpu_master_new.head()
# verify unique hosts
cpu_master_new["hostName"].unique()

array(['10.10.10.65', '10.10.10.150', '10.10.10.2'], dtype=object)

In [11]:
# CPU Dataset information
cpu_master_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6372 entries, 0 to 6371
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                6372 non-null   int64
 1   ts                6372 non-null   datetime64[ns, UTC]
 2   host_id           6372 non-null   int64
 3   cpu_usage_pct     6372 non-null   float64
 4   memory_usage_pct  6372 non-null   float64
 5   power_kw          6372 non-null   float64
 6   temperature_c     6372 non-null   int64
 7   status            6372 non-null   object
 8   hostName          6372 non-null   object
 9   ilo_server_id     6372 non-null   int64
 10  inlet_temp_c      6372 non-null   int64
 11  cpu_temp_c        6372 non-null   int64
 12  processor_count   6372 non-null   int64
dtypes: datetime64[ns, UTC](1), float64(3), int64(7), object(2)
memory usage: 647.3+ KB

In [12]:
# missing values check
cpu_master_new.isnull().sum()

id                  0
ts                  0
host_id             0
cpu_usage_pct       0
memory_usage_pct    0
power_kw            0
temperature_c       0
status              0
hostName            0
ilo_server_id       0
inlet_temp_c        0
cpu_temp_c          0
processor_count     0
dtype: int64

In [13]:
# duplicate check
cpu_master_new.duplicated().sum()

np.int64(0)

In [14]:
# timestamp range
print("Earliest Timestamp:")
print(cpu_master_new["ts"].min())

print("\nLatest Timestamp:")
print(cpu_master_new["ts"].max())

Earliest Timestamp:
2026-06-11 00:01:37.268000+00:00

Latest Timestamp:
2026-06-18 08:56:45.839000+00:00

In [15]:
# Sort dataset
cpu_master = cpu_master_new.sort_values(
    ["hostName", "ts"]
)

In [16]:
# reset index
cpu_master = cpu_master_new.reset_index(
    drop=True
)

In [17]:
# save processed dataset
Path("../data/Processed").mkdir(
    parents=True,
    exist_ok=True
)
cpu_master.to_csv(
    "../data/Processed/cpu_master_new.csv",
    index=False
)

In [18]:
print(cpu_master_new.shape)

cpu_master.head()

(6372, 13)

,id,ts,host_id,cpu_usage_pct,memory_usage_pct,power_kw,temperature_c,status,hostName,ilo_server_id,inlet_temp_c,cpu_temp_c,processor_count
0,74125,2026-06-11 00:01:37.268000+00:00,1,2.03,81.65,0.220,27,Warning,10.10.10.65,1,27,41,2
1,74128,2026-06-11 00:06:36.561000+00:00,1,2.03,81.65,0.221,28,Warning,10.10.10.65,1,28,43,2
2,74131,2026-06-11 00:11:42.330000+00:00,1,1.88,81.65,0.220,23,Warning,10.10.10.65,1,23,41,2
3,74134,2026-06-11 00:16:37.251000+00:00,1,2.78,81.65,0.221,20,Warning,10.10.10.65,1,20,39,2
4,74137,2026-06-11 00:21:36.482000+00:00,1,3.31,81.65,0.220,25,Warning,10.10.10.65,1,25,40,2